name: build

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        export R_LIBS=$HOME/R/library
        mkdir -p $R_LIBS
        Rscript --no-restore --no-save -e 'install.packages("shiny", lib = Sys.getenv("R_LIBS"), repos="https://cran.rstudio.com/")'
        Rscript --no-restore --no-save -e 'install.packages("shinydashboard", lib = Sys.getenv("R_LIBS"), repos="https://cran.rstudio.com/")'
        Rscript --no-restore --no-save -e 'install.packages("RSQLite", lib = Sys.getenv("R_LIBS"), repos="https://cran.rstudio.com/")'
        Rscript --no-restore --no-save -e 'install.packages("plotly", lib = Sys.getenv("R_LIBS"), repos="https://cran.rstudio.com/")'
        Rscript --no-restore --no-save -e 'install.packages("rsconnect", lib = Sys.getenv("R_LIBS"), repos="https://cran.rstudio.com/")'
        Rscript --no-restore --no-save -e 'install.packages("tidyverse", lib = Sys.getenv("R_LIBS"), repos="https://cran.rstudio.com/")'
        Rscript --no-restore --no-save -e 'install.packages("dplyr", lib = Sys.getenv("R_LIBS"), repos="https://cran.rstudio.com/")'

    - name: Build app
      run: Rscript -e "shiny::runApp('R/app.R')"
