name: build

on:
  push:
    branches: [main]

jobs:

  build:
    
    runs-on: ubuntu-latest
    
    env:
      SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
    
    strategy:
      matrix:
        config:
          - r: '4.1'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.config.r }}
        # Enable RStudio Package Manager to speed up package installation
        use-public-rspm: true

    - name: Set up dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::covr
        needs: coverage

    - name: Test coverage
      run: |
        covr::codecov(
          quiet = FALSE,
          clean = FALSE,
          install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
        )
      shell: Rscript {0}

    - name: Show testthat output
      if: always()
      run: |
        ## --------------------------------------------------------------------
        find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
      shell: bash

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-test-failures
        path: ${{ runner.temp }}/package