name: build

on:
  push:
    branches: [main]

jobs:

  build:
    
    runs-on: ubuntu-latest
    
    env:
      SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
    
    strategy:
      matrix:
        config:
          - r: '4.1'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.config.r }}
        # Enable RStudio Package Manager to speed up package installation
        use-public-rspm: true

    - name: Install dependencies
      run:
          export R_LIBS=$HOME/R/library
          mkdir -p $R_LIBS
          Rscript -e 'install.packages("shiny", lib = Sys.getenv("R_LIBS"), repos="https://cran.rstudio.com/")'
          Rscript -e 'install.packages("shinydashboard", lib = Sys.getenv("R_LIBS"), repos="https://cran.rstudio.com/")'
          Rscript -e 'install.packages("RSQLite", lib = Sys.getenv("R_LIBS"), repos="https://cran.rstudio.com/")'
          Rscript -e 'install.packages("dplyr", lib = Sys.getenv("R_LIBS"), repos="https://cran.rstudio.com/")'
          Rscript -e 'install.packages("tidyverse", lib = Sys.getenv("R_LIBS"), repos="https://cran.rstudio.com/")'
          Rscript -e 'install.packages("plotly", lib = Sys.getenv("R_LIBS"), repos="https://cran.rstudio.com/")'
          Rscript -e 'install.packages("rsconnect", lib = Sys.getenv("R_LIBS"), repos="https://cran.rstudio.com/")'

    - name: Build app
      run: Rscript -e 'shiny::runApp("EduAttain/app.R")'

    - name: Deploy to shinyapps.io
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: Rscript -e 'rsconnect::deployApp("EduAttain/app.R")'