name: build

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        install.packages(c("shiny", "shinydashboard", "RSQLite", "dplyr", "tidyverse", "plotly", "rsconnect"))
      shell: Rscript {0}

    - name: Build app
      run: shiny::runApp('R/app.R')
      shell: Rscript {0}
