name: build

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: [os: ubuntu-latest, r: 'release']

    - name: Checkout repo
        uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.config.r }}
        # Enable RStudio Package Manager to speed up package installation
        use-public-rspm: true

    - name: Install and cache dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck

    - name: Build app
      run: shiny::runApp('R/app.R')
      shell: Rscript {0}

    - name: Deploy to shinyapps.io
        # Continuous deployment only for pushes to the main / master branch
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: Rscript deploy/deploy-shinyapps.R