name: build

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        export R_LIBS=$HOME/R/library
        mkdir -p $R_LIBS
        install.packages(c("shiny", "shinydashboard", "RSQLite", "dplyr", "tidyverse", "plotly", "rsconnect"), lib = Sys.getenv("R_LIBS"), repos="https://cran.rstudio.com/")'
      shell: Rscript {0}

    - name: Build app
      run: shiny::runApp('R/app.R')
      shell: Rscript {0}